baseURL = '/'
languageCode = 'fa-ir'
title = 'تصفیه روغن ترانس'
theme = 'hugo-seven'

# تنظیمات تم Hugo Seven
[params]
  # اطلاعات سایت
  description = "تصفیه روغن ترانس"
  author = "فیلترانس"
  copyright = "© 2024 تمامی حقوق محفوظ است"
  
  # تنظیمات لوگو
  logo = "images/logo.png"
  
  # تنظیمات منو
  [[params.menu]]
    name = "خانه"
    url = "/"
    weight = 1
  [[params.menu]]
    name = "مقالات"
    url = "/blog/"
    weight = 2
  [[params.menu]]
    name = "درباره ما"
    url = "/about/"
    weight = 3
  [[params.menu]]
    name = "تماس"
    url = "/contact/"
    weight = 4

# تنظیمات زبان
[languages]
  [languages.fa]
    languageName = "فارسی"
    weight = 1
    contentDir = "content/fa"
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
  [languages.ar]
    languageName = "العربی"
    weight = 1
    contentDir = "content/ar"
